### ISSUE TITLE
Add argument for "sleep time" between clone due to rate-limit

### ISSUE THREAD

**Issue by smesguich-orange** [ezbz/gitlabber#102]
Hello

Is it possible to implement a simple "sleep time" between clone with a argment like `--sleep 10` due to rate limit on gitlab ?

Regards

**Comment by ezbz** [comment]
Python gitlab implements rate limiting and obeys gitlabs throttling, see: https://python-gitlab.readthedocs.io/en/v3.0.0/api-usage.html#:~:text=Rate%20limits,header%20that%20GitLab%20sends%20back.
