### ISSUE TITLE
Cloning Subgroups doesnt work

### ISSUE THREAD

**Issue by wangyucui1002926** [ezbz/gitlabber#105]
I've launched the following command
`gitlabber -t **** -u https://gitlab.***.cn -i  '/roche-digital-platform/devops** -m http'  . `

it says, after many seconds:

`2022-12-07 16:16:05,042 - gitlabber.cli - CRITICAL - The tree is empty, check your include/exclude patterns or run with more verbosity for debugging`

But when I launched the following command ,it works ,the repo can be cloned
`gitlabber -t **** -u https://gitlab.***.cn/ -m http`

**Comment by fsword7** [comment]
I have same problem when I tried to clone xorg group from gitlab.freedesktop.org.
