### ISSUE TITLE
Self signed certificate support

### ISSUE THREAD

**Issue by g0ddest** [ezbz/gitlabber#106]
It will be nice to have an opportunity to pin own CA certificate or skip certificate error that is happen when trying to use with gitlab with self-signed SSL certificate:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='gitlab.example.com', port=443): Max retries exceeded with url: /api/v4/groups (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))`

**Comment by guadaduche** [comment]
Hi
I have same issue as @g0ddest 
I agree, it could be nice to ignore ssl certificate verify
Do you have an advice to ignore this ? (which code to edit ?)
Thx

**Comment by s00ner** [comment]
I'm in the same boat, really would appreciate a flag to ignore SSL validation issues.

**Comment by JosephBowkett** [comment]
You can already use a self signed certificate by setting the OS environment variable `REQUESTS_CA_BUNDLE` to the path of your self signed cert, which is used inside the `get_ca_path()` function of script `gitlab_tree.py` : https://github.com/ezbz/gitlabber/blob/master/gitlabber/gitlab_tree.py#L47

For example, on Ubuntu I ran: `REQUESTS_CA_BUNDLE=/etc/ssl/certs/some.website.com.pem /home/user/.local/bin/gitlabber -t gItLabperSoNalTokeN -p -u https://some.website.com` which still complains about SSL but works.
