### ISSUE TITLE
Does not grab all branches/tags

### ISSUE THREAD

**Issue by dkrystall** [ezbz/gitlabber#11]
I ran the tool on a gitlab instance and when i went to move it, it didn't have any of the other branches or tags for many of the repositories. Does this do a clone operation for the default branch? Was wondering if there might be arguments I missed for grabbing everything.

**Comment by ezbz** [comment]
Just performs a `git clone -v <repo_url>`. I believe there's an option to provide additional arguments.

There's an option to provide additional parameters as specified here: https://gitpython.readthedocs.io/en/stable/reference.html?highlight=clone_from#module-git.repo.base

**Comment by elmart-devo** [comment]
Sorry, I don't get it. I'm trying to understand if I can tweak the git clone made by gitlabber. Specifically, to make a shallow clone of default branch: `git clone --depth 1 <url>`.

**Comment by ezbz** [comment]
Currently this functionality is not provided, however it could be according to [this](https://github.com/gitpython-developers/GitPython/issues/269).

Just need to think on how to implement additional git arguments in the cli.

**Comment by hacknug** [comment]
> Currently this functionality is not provided, however it could be according to [this](https://github.com/gitpython-developers/GitPython/issues/269).
> 
> Just need to think on how to implement additional git arguments in the cli.

anything we can do to help bring this to life?
