### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by hashworks** [ezbz/gitlabber#116]
Over two years have passed since the last tag, and there have been at least [some commits since then](https://github.com/ezbz/gitlabber/compare/v1.1.9...master).

Could you create a new tag?

**Comment by odin568** [comment]
... thinking the same. 
Additionally, there are some PRs fixing some known problems which are ready to be merged (like https://github.com/ezbz/gitlabber/pull/72).
Would be really happy to see some activities from maintainers here - as this project is pretty awesome and I use it regulary!

**Comment by ezbz** [comment]
1.2.0 released
