### ISSUE TITLE
Unable clone any repo from gitlab.freedesktop.org

### ISSUE THREAD

**Issue by fsword7** [ezbz/gitlabber#123]
I tried to clone a group called 'xorg' includes subgroups but it always show empty tree.

gitlabber -t **** -u https://gitlab.freedesktop.org -i '/xorg**' -m http .

I got a message said that:

2024-02-12 09:03:04,393 - gitlabber.cli - CRITICAL - The tree is empty, check your include/exclude patterns or run with more verbosity for debugging

Does anyone able clone entire xorg group with subgroups?  I am using Ubuntu system.

How about mirroring feature like 'git clone --mirror'.  I did not see any feature support in gitlabber.

Thanks,
Tim

**Comment by ezbz** [comment]
Assuming you are using a personal access token I don't think you have permission to read_repository on the entire https://gitlab.freedesktop.org/ gitlab, have you tried doing these API calls using cURL first?

I am not sure gitlabber is meant for these kind of servers, it is a huge repository

**Comment by ezbz** [comment]
no response, closing
