### ISSUE TITLE
Tree is confused by sub-groups

### ISSUE THREAD

**Issue by liljenstolpe** [ezbz/gitlabber#13]
Greetings,

I have a project 'P' that is in group 'G' and sub-group 'S'.  When I run gitlabber -p, I see
```
root [https://gitlab.com]
|---G [/G]
|      |---S [/G/S/]
|      |      |---P [/G/S/P]
|
|---S [/S]
|      |---P [/S/P]
```
Similarly, I have copies of P's repo in repo/G/S/P and repo/S/P.  In both cases the remote points back to the correct location /G/S/P

In a complex set of projects and sub-projects - this creates a bit of a mess...

Christopher

**Comment by ezbz** [comment]
For some reason (not sure when this started) the Gitlab [Groups API] on Gitlab.com (https://docs.gitlab.com/ee/api/groups.html) started returning `subgroups` as well, not sure if this is a bug or a feature but I added a check to filter out subgroups when fetching top level groups.

**Comment by liljenstolpe** [comment]
Thx.
