### ISSUE TITLE
Use system CA certs for SSL connections

### ISSUE THREAD

**Issue by emanspeaks** [ezbz/gitlabber#14]
My office's GitLab server uses an SSL cert that Python out of the box doesn't seem to like.  After much searching, I came across a solution that I was able to splice in and make Gitlabber finally work.  I'm mostly writing an issue now as a braindump and at some point I can try to create a PR from my personal laptop.

```
...

# see https://stackoverflow.com/a/50215614
import requests
from requests.adapters import HTTPAdapter
# from requests.packages.urllib3.util.ssl_ import create_urllib3_context
from ssl import create_default_context

class SSLContextAdapter(HTTPAdapter):
    def init_poolmanager(self, *args, **kwargs):
        context = create_default_context()  # create_urllib3_context()
        kwargs['ssl_context'] = context
        context.load_default_certs() # this loads the OS defaults on Windows
        return super(SSLContextAdapter, self).init_poolmanager(*args, **kwargs)


def get_system_cert_context(url):
    s = requests.Session()
    adapter = SSLContextAdapter()
    s.mount(url, adapter)
    s.get(url)
    return s


class GitlabTree:

    def __init__(self, url, token, method, includes=[], excludes=[], in_file=None, concurrency=1, disable_progress=False):
        self.includes = includes
        self.excludes = excludes
        self.url = url
        self.root = Node("", root_path="", url=url)

        self.gitlab = Gitlab(url, private_token=token,
                             session=get_system_cert_context(url))

...
```

**Comment by alaczyz** [comment]
Hi,
 @emanspeaks  
I have the same issue and your code solves it. Can you create PR?
Best regards,
Ala

**Comment by heltewig-fisp** [comment]
Hi, I second that PR.
Same problem here, self-signed corporate CA.
Unfortunately, I have no clue where to start modding my local installation of gitlabber...

Best regards,
Sebastian

**Comment by gargoylexxx** [comment]
Just to share here, am using self-signed corporate CA too. Since i am lazy to grab CA cert from network and security team, i just modify a bit on the local gitlabber code instead to skip all SSL verification.

Edit in the local library file "**gitlab-tree.py**", and add `ssl_verify=False` to the Gitlab object

`        self.gitlab = Gitlab(url, private_token=token, ssl_verify=False)`

This is an insecure method.
