### ISSUE TITLE
Gitlabber should use the token(s) from .git-credentials

### ISSUE THREAD

**Issue by JohannLange** [ezbz/gitlabber#18]
In case no token is supplied via the `-t` flag and the environmental variable `GITLAB_TOKEN` is empty, gitlabber should try to read the `.git-credentials` file and look for a matching token.

A lot of people already use a personal access token to authenticate themselves, which can also be potentially used by gitlabber.
These access tokens are saved in the `.git-credentials` file inside  users home directory.
The file is just a list of all access tokens in the format

```
https://username:token@gitlab.url
```

Thus, gitlabber can try to read the file and see if a matching access token exists.

**Comment by kitos9112** [comment]
I'd love to see this feature indeed! I had to export my personal token to be able to clone all repos.

Having this functionality would be top

**Comment by ezbz** [comment]
GitPython doesn't officially support [this](https://stackoverflow.com/questions/44784828/gitpython-git-authentication-using-user-and-password) neither does gitlabber you can easily create your own wrapper and askypass.py to do it
