### ISSUE TITLE
Cloning Subgroups doesnt work

### ISSUE THREAD

**Issue by TobiMiller** [ezbz/gitlabber#24]
Why is it not working?

```
gitlabber -t TOKEN -u https://git.HOST.de/ -i "/Group/SubGroup**" .

2020-08-04 12:08:14,737 - gitlabber.cli - INFO - Reading projects tree from gitlab at [https://git.HOST.de/]
2020-08-04 12:08:18,931 - gitlabber.cli - ERROR - The tree is empty, check your include/exclude patterns or run with more verbosity for debugging

```

**Comment by quintanilha6** [comment]
Hello! I have a huge tree that I can get from running  `gitlabber -p -t <token> -u https://gitlab.cern.ch .`

`root [https://gitlab.cern.ch]
├── ai [/ai]
│   └── ....
├── AIGROUP-es-monit-kibana-cms [/AIGROUP-es-monit-kibana-cms]
│   ├── ....
├── All-Hadronic-Four-Top [/All-Hadronic-Four-Top]
│   └── ....
├── cms-analysis [/cms-analysis]
│   └── general [/cms-analysis/general]
│       └── ....
├── cms-b2g [/cms-b2g]
│   ├── ....
├── .....
│   └── B2G-16-027 [/cms-b2g-hepdata/B2G-16-027].
├── CMSDCS [/CMSDCS]
│   ├── Conferences [/CMSDCS/Conferences]
│   │   └──....
│   ├── DB [/CMSDCS/DB]
│   │   ├── ....
│   ├── DCS [/CMSDCS/DCS]
│   │   ├── ....
│   │   ├── DCS_COMPONENTS [/CMSDCS/DCS/DCS_COMPONENTS]
│   │   │   └── TRIGGER [/CMSDCS/DCS/DCS_COMPONENTS/TRIGGER]
│   │   │       └── ....
│   │   ├── ....
│   ├── web [/CMSDCS/web]
│   │   ├──....
│   ├── Documentation [/CMSDCS/Documentation]
│   └── WTS [/CMSDCS/WTS]`

My intention is to clone every project that is inside the `web` subgroup of my `CMSDCS` group. I have tried running:

`gitlabber -i '/CMSDCS/web**' -t <token> -u https://gitlab.cern.ch .`
and also
`gitlabber -i '/CMSDCS' -t <token> -u https://gitlab.cern.ch .`

But I get `gitlabber.cli - CRITICAL - The tree is empty, check your include/exclude patterns or run with more verbosity for debugging`

So, even-though I get the full tree, I guess I'm doing something wrong on the cloning? Any help?
