### ISSUE TITLE
use project path instead of project name

### ISSUE THREAD

**Issue by Darkein** [ezbz/gitlabber#25]
Hello,

it would be nice if it was possible to generate folder name based on project path, because the name doesn't always reflect the correct project path.

For exemple i have theses projects

```
root
├── Project 1 [/project1]
|   ├── Project 1 Front [/project1/front]
|   └── Project 1 Api [/project1/api]
└── Project 2 [/project2]
    ├── Project 2 Front [/project2/front]
    └── Project 2 Api [/project2/api]
```

it creates the following folders
```
root
├── Project 1
|   ├── Project 1 Front
|   └── Project 1 Api
└── Project 2
    ├── Project 2 Front
    └── Project 2 Api
```

but I would like
```
root
├── project1
|   ├── front
|   ├── api
└── project2
    ├── front
    └── api
```

**Comment by rodamaral** [comment]
Please, consider at least falling back to the actual URL when the name of the project is not found in the repository. If it wasn't for _this issue_, I'd not be able to figure out why the command was failing.

**Comment by ezbz** [comment]
Gitlab doesn't impose uniqueness of names for groups and projects filesystems do, the only  deterministic thing to do is use path

https://gitlab.com/gitlab-org/gitlab-foss/-/issues/37129
