### ISSUE TITLE
docs: mention python-certifi-win32

### ISSUE THREAD

**Issue by shoffmeister** [ezbz/gitlabber#29]
This is somewhat outland-ish, but most likely enabling in a number of scenarios:

Often, gitlab will be installed on-premise, and the certificate for HTTPS will be self-signed, from a private CA. This would be a typical enterprise deployment.

Python on Linux (IIRC - cannot validate right now) will be configured by distributions to (also) point to their (system) CA store.

Python on Windows needs a little bit of help - I just found https://pypi.org/project/python-certifi-win32/ to be extremely helpful in allowing Python to use the CA certificate(s) which are already installed in the Windows (system) certificate store.

If this information about CA certificate stores could be added to the docs, then user experience for gitlabber might be improved:

    https://enterprise-gitlab.example.com

will not throw trust exceptions, will just work, also with Windows clients (obviously, the python-certifi-win32 would have to be installed by the user).

**Comment by ezbz** [comment]
thanks for the contribution will add it to the documentation
