### ISSUE TITLE
gitlabber keeps asking for entering password of the gitlab account 

### ISSUE THREAD

**Issue by ktaa13** [ezbz/gitlabber#3]
when i run gitlabber with access token and gitlab URL, it keeps prompting for a password. I tried to add the access token and the gitlab password but is kept prompting again and wasn't cloning the repositories

**Comment by ezbz** [comment]
The access token and URL are for accessing the gitlab API.

The password prompt is for cloning the repositories. Type your gitlab username and password to clone the repositories.

**Comment by ktaa13** [comment]
I tired but it still keeps prompting and doesn’t clone the repository

**Comment by ezbz** [comment]
means you don't have permissions, did you try to clone the repository directly (without gitlabber)?

can you please run

```export GIT_PYTHON_TRACE='full'```

and then run gitlabber again with the `--debug` flag and post the output here?

**Comment by dkrystall** [comment]
I'm having the same issue, it looked like it was trying to access the repo's over ssh given the token and the url. It didn't prompt for a username/pw like it would over https, just a password field. I can access the repositories over https just fine.
Do I need to setup an ssh key?

**Comment by dkrystall** [comment]
> I'm having the same issue, it looked like it was trying to access the repo's over ssh given the token and the url. It didn't prompt for a username/pw like it would over https, just a password field. I can access the repositories over https just fine.
> Do I need to setup an ssh key?

Yeah I setup an ssh key and it seems to be working fine 👍  Think you'll add HTTPS support in the future?

**Comment by lnksz** [comment]
Similar issue here. But I am not allowed to use ssh, so I am stuck

**Comment by ezbz** [comment]
#10 adds support for http-based cloning, gitlabber will use the `http_url_to_repo` from Gitlab API (see https://docs.gitlab.com/ee/api/projects.html)
