### ISSUE TITLE
Doesn't work with cloudflare

### ISSUE THREAD

**Issue by androidacy-user** [ezbz/gitlabber#30]
Cloudflare will complain no host header was sent if it isn't specified

**Comment by rhysjtevans** [comment]
@unixandria-xda Did you manage to work around it? Having the same problem here?

**Comment by unixandria-xda** [comment]
> @unixandria-xda Did you manage to work around it? Having the same problem here

No, I ended up cURLing the json directly

**Comment by ezbz** [comment]
@androidacy did you try adding the host header to the HTTP request and see if it solves the problem?
