### ISSUE TITLE
Subgroups get cloned many Times

### ISSUE THREAD

**Issue by fwidder** [ezbz/gitlabber#32]
Using GitLab, if you have the following Project-Structure:

`myGroup/mySubGroup/mySubSubGroup`

and run following Command:

`gitlabber -t "**************************" -u "https://git.HOST.com" -m ssh .`

Then mySupSupGroup will be Cloned three times:

```
.
├── myGroup
│   └── mySupGroup
│       └── mySupSupGroup
├── mySupGroup
│   └── mySupSupGroup
└── mySupSupGroup

```
---
Editional Information:
Gitlabber Version: 1.1.0
Gitlab Version: GitLab Enterprise Edition 13.4.3-ee
OS: Linux Mint 20
Git Version: 2.25.1

**Comment by ezbz** [comment]
Fixed by https://github.com/ezbz/gitlabber/pull/27
