### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by trifwn** [ezbz/gitlabber#34]
On Python 3.8.5 after pip install The command "gitlabber -t ####### -p" exits with AttributeError: 'NoneType' object has no attribute 'rstrip', as does any attempt to clone or pull anything

**Comment by komali2** [comment]
I think the URL flag is required, with a URL, and the examples just fail to indicate that.

**Comment by ezbz** [comment]
the examples assume you understand the interaction with environment variables so when the url is omitted in the example it's assumed that it is provided by the url I will clarify that in the examples
