### ISSUE TITLE
How to specify ssh key to be used?

### ISSUE THREAD

**Issue by Rigel772** [ezbz/gitlabber#42]
I have multiple Gitlab accounts - cannot use the same ssh key for all so I have multiple keys in my .ssh folder...
I dont need to all accounts to be cloned at once, can do it one by one but how to specify which key should be used?
Thanks, great project!

**Comment by ezbz** [comment]
Gitlabber uses [GitPython](https://gitpython.readthedocs.io/en/stable/), it could be theoretically achieved with GitPython as described [here](https://medium.com/@tzuni_eh/git-commit-with-gitpython-and-ssh-key-926cad91ca89) but this not something I think should be implemented for gitlabber.

I suggest you clone with HTTP as the method and provide the token for each gitlab account via the CLI.

If you have to rely on SSH you need to do some SSH trickery between the commands to achieve this.

**Comment by Rigel772** [comment]
Ok, thanks

**Comment by ezbz** [comment]
@Rigel772 can I close this?

**Comment by Rigel772** [comment]
Sure, sorry, forgot.
