### ISSUE TITLE
Command CLI Usage

### ISSUE THREAD

**Issue by rider8581** [ezbz/gitlabber#64]
Thank you for shaing this awesome project.

For example, if I need to clone the following group, how should I input cli args?

https://gitlab.com/kalilinux 

Kindly guide me, thanks

**Comment by ezbz** [comment]
Follow the instructions to grab an access token then I think this should do the trick for you:

```
gitlabber -t TOKEN -u 'https://gitlab.com/' -i '/kalilinux**' -n path .
```

**Comment by rider8581** [comment]
thank you for your reply, I tried but got following error:
![image](https://user-images.githubusercontent.com/52605718/112292122-ac5aba00-8c88-11eb-8622-fb39cd00159f.png)
Would you check what the issue is?

**Comment by ezbz** [comment]
Well this command should work for you if the project path is as you provided, I suggest you look into the project name/path and try to figure out what is missing (if you want to use group names instead of server paths remove the `-n path` parameter from the command
