### ISSUE TITLE
Shouldn't retrieve moved projects

### ISSUE THREAD

**Issue by Crocmagnon** [ezbz/gitlabber#69]
```
$ gitlabber -p -i "/mygroup/**" -a exclude
root [https://git.example.com]
└── mygroup [/mygroup]
    ├── valid1 [/mygroup/valid1]
    ├── non-existant [/mygroup/non-existant]
    ├── valid2 [/mygroup/valid2]
    └── valid3 [/mygroup/valid3]
```

I'm pretty sure that this project was here before but has since been moved elsewhere.
When cloning, the project is cloned with a remote matching its new location.

Expected behavior:
The `non-existant` project shouldn't be retrieved.

**Comment by ezbz** [comment]
Strange, I seem to recall documenting the fact that gitlabber doesn't maintain local state and doesn't support project movements on the server, is this the situation you are referring to? If you move a project it's your responsibility to remove it from the local tree in the old location and it will be cloned in the new location.

**Comment by Crocmagnon** [comment]
> is this the situation you are referring to?

Not quite. Here's how to reproduce:

1. Create a project in a gitlab group
2. Move the project to another, unrelated group
3. Run gitlabber for the first time

Gitlabber retrieves the phantom project.

**Comment by ezbz** [comment]
So the project is in fact being returned by the [projects API](https://docs.gitlab.com/ee/api/projects.html), perhaps the old path is now archived and you need to exclude it from the results?

**Comment by Crocmagnon** [comment]
I don’t have access to my computer now but yeah it’s probably being returned by the api since that’s what you’re based on.
I’ll check if the raw api returns it.

The project hasn’t been archived, it has however been moved to another group (to which I have access).

I’ll report it on the relevant project (python-gitlab or gitlab directly), thanks !

**Comment by Crocmagnon** [comment]
I can confirm it's being returned by Gitlab's API. Strangely I can't reproduce it on a new project 😕
