### ISSUE TITLE
Clone/pull by a group id

### ISSUE THREAD

**Issue by konfetka1989** [ezbz/gitlabber#86]
If you have access to a large amount of groups, it may take much time to load an entire tree. It would be nice to have an opportunity to specify an exact group id which you want to clone.

I propose my solution:
https://github.com/konfetka1989/gitlabber/commit/e48c267c351ea7e591d4d502e52ec123563eea03

Please consider it. Thanks.

I didn't create a pull request, because CONTRIBUTING.md states I have to discuss my changes with the owner first.

**Comment by konfetka1989** [comment]
Hi @ezbz 

I created a draft pull request which provides a new approach to using some group as a root:
https://github.com/ezbz/gitlabber/pull/89

Could you please review it? Thank you.

**Comment by radoslav006** [comment]
Hi everybody!
It will be very helpful for me as unfortunately I am hitting gitlab rate limits, so - sadly - I cannot use this tool. AFAIU this merge request should limit the number of http requests.

**Comment by ezbz** [comment]
> Hi everybody! It will be very helpful for me as unfortunately I am hitting gitlab rate limits, so - sadly - I cannot use this tool. AFAIU this merge request should limit the number of http requests.

Python gitlab implements rate limiting and obeys gitlab's throttling, see: https://python-gitlab.readthedocs.io/en/v3.0.0/api-usage.html#:~:text=Rate%20limits,header%20that%20GitLab%20sends%20back.
