### ISSUE TITLE
Error: Please specify a destination for the gitlab tree

### ISSUE THREAD

**Issue by vjwilson1987** [ezbz/gitlabber#90]
I am trying to clone an entire gitlab tree using a base url and a token.

When running the command:

```
$ gitlabber -t ~/.ssh/gitlab_key -u https://gitlab.com/mygroupname
Please specify a destination for the gitlab tree
```

Please correct me if I am doing it in the wrong way.

**Comment by vjwilson1987** [comment]
Another try:

```
gitlabber -t https://<token_name>:<token_access>@gitlab.com -u https://gitlab.com/mygroupname
Please specify a destination for the gitlab tree
```

What is the correct way?.

**Comment by ezbz** [comment]
1. for the gitlab token you need to provide the actual token value and not a file `~/.ssh/gitlab_key' or a uri `https://<token_name>:<token_access>@gitlab.com`
2. `-u` parameter os for the base url, e.g., `https://gitlab.com/` and not `https://gitlab.com/mygroupname`
3. the last parameter of the command tells gitlabber where to clone the root of the tree please try the following command to clone it to the current directory  (`.`):


```
gitlabber -t <personal access token> -u <gitlab url> .
```

Please refer to the examples section of the documentation for more information on how to use gitlabber

**Comment by adesinayinka** [comment]
I have cloned all my orgs private repository into my local computer. Now I need a way to push to a group I created on Gitlab. Is there a gitlabber command for that?
