### ISSUE TITLE
SSL Certificate suport

### ISSUE THREAD

**Issue by fil-monterey** [ezbz/gitlabber#91]
**Describe the bug**
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) is created when complete cert chain isn't present

**To Reproduce**
gitlabber -t <token> -u https://company-gitlab.com .

**Expected behavior**
No SSL error should be thrown

**Comment by ezbz** [comment]
AFAIK from this error you need to install python certificates.

See this [link](https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate) for more information

**Comment by radoslav006** [comment]
Helped in my case:
`pip install python-certifi-win32`
