### ISSUE TITLE
python -m gitlabber failed after install from source

### ISSUE THREAD

**Issue by ckelsel** [ezbz/gitlabber#93]
**Describe the bug**
```
$ python2 -m gitlabber
Traceback (most recent call last):
  File "C:\PYTHON27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\PYTHON27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\work\0\0_as\1_open_source_demo\0_astute\gitlabber\gitlabber\__main__.py", line 1, in <module>
    from .cli import main
  File "gitlabber\cli.py", line 32
    elif args.dest is None and args.print is False:
                                        ^
SyntaxError: invalid syntax

```
**To Reproduce**
1. Include the full command line with all arguments and the output in verbose (`-v`) mode
```
git clone https://github.com/ezbz/gitlabber.git
cd gitlabber
python2 setup.py install
python2 -m gitlabber
```
**Expected behavior**
python2 -m gitlabber run success

**Versions (please complete the following information):**
 - OS: [e.g. iOS] and version
 -  Windows 10
 - Python Version [e.g. 2.6]
 - Python 2.7.10
 - Gitlab type [e.g. host, cloud] and Version [e.g. 14.0] where applicable
 - Gitlabber version [e.g. 1.18]
master, commit id 408dd252745fe65252bbc04391a1bceb1f846a26

**Additional context**

**Comment by ezbz** [comment]
gitlabber users python 3, python 2 is not supported
