### ISSUE TITLE
Syncing projects took [None]

### ISSUE THREAD

**Issue by bofomike** [ezbz/gitlabber#96]
**Describe the bug**
After all expected projects are cloned, there's this last message logged:
**2022-01-28 11:59:26,897 - gitlabber.git - DEBUG - Syncing projects took [None]**
I guess [None] is not expected here 

**To Reproduce**
This is the call we are using upon container start:
gitlabber -u https://our_gitlab_url -t $(cat /tmp/gitlab/`ls /tmp/gitlab | head -1`) --verbose -a exclude -i "/Trusted IDentity**" .

**Expected behavior**
Proper value replacing current [None]

**Versions (please complete the following information):**
 - Ubuntu 20.04
 - Python Version: 3.9.7
 - GitLab Enterprise Edition 14.6.2-ee
 - Gitlabber version: 1.1.9

**Comment by ezbz** [comment]
Can you please run you command in verbose mode and place the output here
