### ISSUE TITLE
Gitlabber not cloning repositories, only structure

### ISSUE THREAD

**Issue by Morphosdark** [ezbz/gitlabber#99]
**Describe the bug**
When trying to clone all the repositories of a group, it only creates the tree.

Im using a token with read_api and read_repository.

After the first run, i've run again, and nothing happened

**To Reproduce**

the command i use to run gitlabber:

gitlabber -t MYTOKEN -u MYURL

**Comment by redtux** [comment]
Hi, I can confirm this. Following the instructions in the readme I can connect via SSH, read the tree, and create the skeleton of the respective gitlab instance - but not a single repo is being cloned.

**Comment by redtux** [comment]
Just in case, using another token with full access does not help, while using `--method http` and providing username and password works as expected. (Maybe related to #97.)

**Comment by reznid01** [comment]
Any update for this issue? We are using SSO and it is impossible to provide username, password and MFA for each project. this defeats the purpose for using this module.

**Comment by rdumouchelle** [comment]
Confirming this as well.  This make the entire project unusable.

**Comment by dylanh724** [comment]
Yep confirming - still happening in late 2022; is this project still alive?

**Comment by dylanh724** [comment]
(CC @ezbz - since this is a long-term breaking bug)

**Comment by redtux** [comment]
> Yep confirming - still happening in late 2022; is this project still alive?

Define alive 🤭 According to the git log the last code change was a year ago, and the last commit is seven month old. 🤷🏻‍♂️🙂

**Comment by dylanh724** [comment]
Time to fork? I think a fix [is here](https://github.com/ezbz/gitlabber/pull/98)

**Comment by ogencoglu** [comment]
Any updates on this?

**Comment by mertensr** [comment]
I suggest to use --verbose option to see what is going wrong. **I can confirm that the tool is still working!**
I had the same issue. It looked like the tool is just creating the structure. When I turned on --verbose I found that the "git clone" was failing due to some issues with my ssh keys. Sadly  gitlabbler is silent about this and does not even show a warning if you don't use --verbose.
